try {
    throw Error('Criar um erro propositado!');
} catch (e) {
    console.log(e);
}
